name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies (workspaces)
        run: npm ci

      - name: Run backend tests
        run: npm test --workspace=apps/backend

      - name: Run frontend tests
        run: npm test --workspace=apps/frontend
